### ISSUE TITLE
Implementar validación de sesión de usuario

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas-api#10]
# Descripción

**Como** desarrollador
**Quiero** crear una funcionalidad de validación de sesión
**Para** comprobar que los usuarios que acceden a la página tengan una sesión activa.

# Criterios de validación

- [x] Si un usuario no tiene sesión iniciada será redirigido a la pantalla de login.
- [ ] Los datos de sesión de un usuario se guardarán en una cookie, que será la que valida la sesión con el servidor.
- [ ] Un usuario con cookie de sesión activa regresa a una página restringida, como `dashboard`, podrá acceder sin tener que pasar por la pantalla de login.

**Comment by XxMARRExX** [comment]
Criterio uno validado en el [https://github.com/PS-G1-Lab/control-horas/commit/62caca8ad68901b6598932c9d948d069738dcf04](url).
