### ISSUE TITLE
Crear tabla `classes` en la base de datos

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas-api#11]
# Descripción

**Como** desarrollador
**Quiero** tener una tabla en la base de datos llamada `classes`
**Para** tener persistencia de datos con las clases.

# Criterios de validación

- [x] La tabla de la base de datos se tiene que llamar `classes` 
- [x] Contendrá una clase por cada fila con los siguientes campos en las columnas:
`class_id`, `user_id`, `title`, `subject_id`, `students`, `start_at`, `end`, `date` y `description`
- [x] El `class_id` es una clave primaria, entero y autogenerado
- [x] El `user_id` es una clave foránea del id del profesor que genera la clase, obligatorio
- [x] El `title` es un string de 50 caracteres como máximo, obligatorio
- [x] El `subject_id` es una clave foránea del id de la asignatura, obligatorio
- [x] El `students` es un array con los ids de los alumnos que se inscriben a la clase
- [x] El `start_at` es un timestamp con la hora en la que comienza la clase, obligatorio
- [x] El `end` es un timestamp con la hora en la que finaliza la clase, obligatorio
- [x] El `date` es un formato de fecha con la fecha en la que comienza la clase, obligatorio
- [x] El `description` es un string de 280 caracteres como máximo
- [x] El `price` es un valor con decimales, obligatorio

## Material adicional

![Image](https://github.com/PS-G1-Lab/control-horas-api/assets/43654546/14878835-25b0-4dbc-84b6-97da6cb1afb1)

**Comment by XxMARRExX** [comment]
# Descripción

**Como** desarrollador
**Quiero** tener una tabla en la base de datos llamada `classes`
**Para** tener persistencia de datos con las clases.

# Criterios de validación

- [ ] La tabla de la base de datos se tiene que llamar `classes` 
- [ ] Contendrá una clase por cada fila con los siguientes campos en las columnas:
`class_id`, `user_id`, `title`, `subject_id`, `students`, `start_at`, `end`, `date` y `description`
- [ ] El `class_id` es una clave primaria, entero y autogenerado
- [ ] El `user_id` es una clave foránea del id del profesor que genera la clase, obligatorio
- [ ] El `title` es un string de 50 caracteres como máximo, obligatorio
- [ ] El `subject_id` es una clave foránea del id de la asignatura, obligatorio
- [ ] El `students` es un array con los ids de los alumnos que se inscriben a la clase
- [ ] El `start_at` es un timestamp con la hora en la que comienza la clase, obligatorio
- [ ] El `end` es un timestamp con la hora en la que finaliza la clase, obligatorio
- [ ] El `date` es un formato de fecha con la fecha en la que comienza la clase, obligatorio
- [ ] El `description` es un string de 280 caracteres como máximo, obligatorio

# Notas adicionales

![Image](https://github.com/PS-G1-Lab/control-horas-api/assets/43654546/3b938e86-598e-435c-8493-965bbc1938ab)
