### ISSUE TITLE
Crear tabla `subjects` en la base de datos

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas-api#12]
# Descripción

**Como** desarrollador
**Quiero** tener una tabla en la base de datos llamada `subjects`
**Para** tener registradas las asignaturas de las que se van impartiendo clases.

# Criterios de validación

- [x] La tabla de la base de datos se tiene que llamar `subjects` 
- [x] Contendrá una asignatura por cada fila con los siguientes campos en las columnas:
`subject_id` y `subject`
- [x] El `subject_id` es una clave primaria, entero y autogenerado
- [x] El `subject` es un string de 100 caracteres como máximo, obligatorio que se guardará en mayúsculas

# Notas adicionales

![Image](https://github.com/PS-G1-Lab/control-horas-api/assets/43654546/3e77b27e-8a26-4e91-9727-5df02e4361ce)

**Comment by XxMARRExX** [comment]
**Como** desarrollador
**Quiero** tener una tabla en la base de datos de asignaturas
**Para** tener persistencia de datos con las asignaturas.

# Criterios de validación

- [ ] La tabla de de la base de datos contendrá una asignatura por cada fila y los diferentes campos en las columnas:
nombre de la asignatura, id de la asignatura
- [ ] Las asignaturas deben tener unicidad en dicha tabla.
