### ISSUE TITLE
Crear funcionalidad de crear clases

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas-api#13]

**Comment by XxMARRExX** [comment]
# Descripción

**Como** profesor
**Quiero** crear una clase
**Para** que los alumnos puedan asistir a ellas.

# Criterios de validación

- [ ] Para que las clases sean creadas debe especificarse los siguientes parámetros:
Título, Fecha, Hora de inicio, Hora de finalización y Descripción.
- [ ] En la introducción de los parámetros, cada uno debe ser controlado para que no se introduzcan datos incorrectos.
- [ ] Tras la confirmación de la clase, los datos deben almacenarse en la correspondiente tabla de la base de datos.

**Comment by SilviaGonz** [comment]
Faltaría especificar cómo van a ser controlado dichos parámetros @XxMARRExX
