### ISSUE TITLE
Migrar Back End a Render

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas-api#18]
> [!CAUTION]
> **Historia de usuario cambiada.**
> Después de una gran deliberación sobrevenida, la mejor opción es mantener el repositorio del Back End migrando el deploy a Render, adaptando el código de la base de datos a PostgreSQL, ya que es lo que ofrecen con la capa gratuita.

# Descripción

**Como** desarrollador
**Quiero** migrar la API que controla el Back End de la aplicación a Render.com
**Para** prevenir el fallo de la aplicación a causa de la descontinuación del servicio de FL0.

# Criterios de validación

- [x] Reescribir las directivas de la base de datos para que funcionen con PostgreSQL
- [x] Se debe poder crear un usuario de forma exitosa con la nueva API
- [x] Se debe poder loguear un usuario de forma exitosa con la nueva API

---

_HU Antigua_

~Migrar Back End a repositorio de Front End~

# ~Descripción~

~**Como** desarrollador~
~**Quiero** migrar toda la API que controla el Back End de la aplicación~
~**Para** prevenir el fallo de la aplicación a causa de la descontinuación del servicio de FL0.~

# ~Criterios de validación~

- ~Migrar estructura de carpetas de API al repositorio del Front End~
- ~Reescribir API en las directivas de Astro, para dejar de usar Express~
- ~Se debe poder crear un usuario de forma exitosa con la nueva API~
- ~Se debe poder loguear un usuario de forma exitosa con la nueva API~

**Comment by meidencore** [comment]
Tengo experiencia con deploys en render y el backend no debe tener problemas en la capa gratuita, ojo con que el servicio se duerme por inactividad y los wake ups demoran entre 30seg a 1 min.

Con respecto a la bd
Postgres es lo q ofrece render con el inconveniente de q estará gratis por 3 meses, y si se quiere mantener esa bd se debe de pagar, en caso de q no, tendrian q hacer una salva y volver a hacer otra instancia y migrar los datos de la bd anterior y así cada 3 meses.
