### ISSUE TITLE
Validar contraseña cumpliendo recomendaciones de seguridad

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas-api#2]
# Descripción

**Como** desarrollador, 
**Debo**  validar la contraseña que utilicen los usuarios
**Para** que cumpla todas las recomendaciones de seguridad de los estándares web

# Criterios de validación
especificar patrón

**Comment by nuhacet66** [comment]
Funciona el método ZOD
