### ISSUE TITLE
Validar correo electrónico tras registrarse

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas-api#3]
# Descripción

**Como** desarrollador
**Quiero** validar el correo electrónico de todos los usuarios que se registren en la aplicación
**Para** tener una mayor seguridad.

# Criterios de validación

- [x] Tras registrarse un nuevo usuario, se le enviará un correo electrónico con el que se ha registrado, con la confirmación de su registro.
- [x] El mensaje mostrará un texto que indique que su registro ha sido validado con éxito.

**Comment by nuhacet66** [comment]
Implementación de los mensajes de confirmación al correo electronico para el siguiente Sprint. Código ya realizado.

**Comment by nuhacet66** [comment]
`const express = require('express');
const nodemailer = require('nodemailer');
const crypto = require('crypto');

const app = express();

// Configuración del servicio de envío de correo electrónico
const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: 'tu_correo@gmail.com',
    pass: 'tu_contraseña'
  }
});

// Ruta de registro de usuario
app.post('/registro', (req, res) => {
  // Aquí se registra el usuario en la base de datos
  // Generar un token único para el enlace de validación
  const token = crypto.randomBytes(20).toString('hex');
  const validationLink = https://tudominio.com/validar/${token};

  // Envío del correo electrónico de validación
  const mailOptions = {
    from: 'tu_correo@gmail.com',
    to: 'correo_usuario@ejemplo.com',
    subject: 'Por favor, valida tu correo electrónico',
    html: Por favor, haz clic en el siguiente enlace para validar tu correo electrónico: <a href="${validationLink}">${validationLink}</a>
  };

  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.log('Error al enviar el correo electrónico de validación:', error);
      res.status(500).send('Error al enviar el correo electrónico de validación');
    } else {
      console.log('Correo electrónico de validación enviado:', info.response);
      res.status(200).send('Correo electrónico de validación enviado');
    }
  });
});

app.listen(3000, () => {
  console.log('Servidor en ejecución en el puerto 3000');
});`

**Comment by nuhacet66** [comment]
Hemos decidido usar Resend con express ya que tiene una mejor cohesión con Vercel

**Comment by nuhacet66** [comment]
# Código
@XxMARRExX 

import { Resend } from 'resend';
import express, { Request, Response } from 'express';

const resend = new Resend('re_123456789');
const app = express();

app.get('/', async (req: Request, res: Response) => {
  const { data, error } = await resend.emails.send({
    from: 'onboarding@resend.dev',
    to: 'delivered@resend.dev',
    subject: 'Hello World',
    html: '<strong>it works!</strong>',
  });

  if (error) {
    return res.status(400).json(error);
  }

  return res.status(200).json(data);
})
