### ISSUE TITLE
Registrar una clase nueva en la base de datos

### ISSUE THREAD

**Issue by JuanCarlosAcostaPeraba** [PS-G1-Lab/control-horas-api#5]
# Descripción

**Como** desarrollador
**Quiero** que los datos de una clase que registre un profesor logueado se almacenen en la base de datos
**Para** tener persistencia de datos y que los alumnos puedan inscribirse en ella.

# Criterios de validación

- [ ] Verificar que el dato `Título` que viene del formulario es una string.
- [ ] Verificar que el dato `Hora de inicio` que viene del formulario es un formato de fecha en milisegundos.
- [ ] Verificar que el dato `Hora finalización` que viene del formulario es un formato de fecha en milisegundos y que corresponde con una fecha posterior a la 'Hora de inicio'.
- [ ] Verificar que el dato `Descripción` que viene del formulario es una string.
- [ ] Verificar que el dato `Asignatura` que viene del formulario es una string.
- [ ] Verificar si el dato `Asignatura` ya existe en la base de datos, para evitar duplicidad.
- [ ] Almacenar los datos previamente validados (`Título`, `Hora de inicio`, `Hora finalización`, `Fecha`, `Descripción` y `Asignatura`) en la tabla `classes` de la base de datos.

**Comment by nuhacet66** [comment]
`const { Classes, Subjects } = require('../models'); // Importa los modelos de Sequelize

// Función para validar y almacenar los datos de la clase en la base de datos
async function guardarClase(datosClase) {
    try {
        // Validación de los datos del formulario
        // Verificar que los datos son del tipo correcto y cumplen con los criterios de validación

        // Verificar si la Asignatura ya existe en la base de datos
        const asignaturaExistente = await Subjects.findOne({ where: { nombre: datosClase.asignatura } });
        if (!asignaturaExistente) {
            throw new Error('La Asignatura no existe en la base de datos');
        }

        // Almacenar los datos válidos en la tabla Classes de la base de datos
        const nuevaClase = await Classes.create({
            titulo: datosClase.titulo,
            hora_inicio: datosClase.hora_inicio,
            hora_finalizacion: datosClase.hora_finalizacion,
            fecha: datosClase.fecha,
            descripcion: datosClase.descripcion,
            asignaturaId: asignaturaExistente.id // Asigna el ID de la Asignatura existente
        });

        return nuevaClase;
    } catch (error) {
        throw new Error('Error al guardar la clase en la base de datos: ' + error.message);
    }
}

// Ejemplo de uso
const datosClase = {
    titulo: 'Título de la clase',
    hora_inicio: new Date().getTime(),
    hora_finalizacion: new Date().getTime() + 3600000, // Una hora después de la hora de inicio
    fecha: new Date().toISOString().slice(0, 10), // Fecha actual en formato 'YYYY-MM-DD'
    descripcion: 'Descripción de la clase',
    asignatura: 'Nombre de la asignatura'
};

guardarClase(datosClase)
    .then(nuevaClase => {
        console.log('Clase guardada correctamente:', nuevaClase);
    })
    .catch(error => {
        console.error('Error al guardar la clase:', error);
    });
`
